version: 2
jobs:
  build:
    working_directory: ~/nexus-blobstore-s3
    docker:
      - image: maven:3.5.2
    environment:
      - VERSION: "0.1"
    steps:
      - checkout
      - run: mvn clean install
      - run: ls -alh
      - run: ls -alh target/
      - run: mkdir -p uploads
      - run: cp -r target/nexus-blobstore-s3-1.2.1-SNAPSHOT* uploads/
      - run: ls -alh uploads/
      - run: wget https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_386.zip
      - run: unzip ghr_v0.5.4_linux_386.zip
      - run: chmod +x ghr
      - run: ./ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace v$VERSION uploads/
